---
title: "Project Description"
author: "Krista Noe"
date: "2/26/2021"
output: word_document
---
|            My research examines small mammal communities in natural and mitigated wetlands in WV. The research goal is to determine whether small mammal communities differ between natural and mitigated wetlands in order to determine if mitigated wetlands are providing adequate habitat for small mammal species. These communities consist of species such as deer mice, meadow voles, northern short-tailed shrews, and chipmunks. The design consists of a minimum of two transects at each wetland, each including 25 traps spaced 10 meters apart. Traps are out for one period of 5 nights per each site. Animals are captured, marked, and recaptured. Some wetlands are smaller and so do not have the space to accommodate more transects, however some larger wetlands receive more transects. Transects are spaced 50 meters apart. Mitigated wetlands are paired with natural wetlands in the same ecoregion, and have similar elevation and Cowardin classification. 

|            I am interested in addressing the following questions with this research. Does species richness, diversity, and evenness differ significantly between natural and mitigated wetlands? Does vegetative diversity influence species diversity at sites? Does species diversity differ among the different cover categories of vegetation (ex. Shrubs, Herbs, Trees) at each site? Do natural and mitigated wetlands statistically differ in vegetative diversity and richness? Does the average canopy cover in a trap line influence the amount of captures? Do species richness and diversity differ by Cowardin classification type? Although there are different defining features that comprise an ecoregion, which could lead to observed differences in data, I would be interested in determining if differences in captures exists among the types. I would also like to investigate a reason why I experienced so many more captures in the Monongahela National Forest (even at a mitigated wetland site) than at sites not in the Monongahela National Forest. 

|            I have collected data on the species that were captured at each trap at each site, as well as vegetation data. When species were captured, variables about the individual that were recorded were the species, head length and tail length if *Peromyscus spp.*, total length, weight, sex, age group, and the individual's ID. Other variables relating to capture that were recorded were the site, transect and trap ID, what day during the trapping period (1-5), date, time, whether there was rain since the last trap check, and whether water was present (and how much) at the trap. Vegetation data collection included plant ID in a 1 x 1m^2 quadrat and the cover class (ranging from 1-6) of that plant. Canopy cover was also recorded at quadrat corners and leaf litter depth was obtained if present. My response variable would pertain to my captures (this could be species diversity, richness, evenness, abundance, and occupancy, depending on the question). My predictor variables would be whether the wetland is mitigated or natural and vegetation influence. 

|            Something unique about the dataset is that I currently have 6 mitigated wetlands and 4 natural wetlands; although it was initially my intent for this to be a 1:1 ratio and have sets of pairs. Moreover, one of the mitigated wetlands only had one capture (a singular *Peromyscus maniculatus*) for the duration of the 5-day trapping period. 

